import type { Client, Project, Lead, FinanceRecord, CaseStudy, DashboardKPIs } from "./types";

// ─── Mock Clients ─────────────────────────────────────────────────────────────
export const mockClients: Client[] = [
    {
        id: "c1",
        name: "Ahmed Ben Ali",
        company: "TechStart Tunis",
        email: "ahmed@techstart.tn",
        phone: "+216 20 123 456",
        timezone: "Africa/Tunis",
        country: "Tunisia",
        notes: "Prefers communication via WhatsApp. Decision maker.",
        createdAt: "2025-01-15",
        totalBilled: 4800,
        projectIds: ["p1"],
    },
    {
        id: "c2",
        name: "Sarah Dupont",
        company: "EcomParis",
        email: "sarah@ecomparis.fr",
        phone: "+33 6 12 34 56 78",
        timezone: "Europe/Paris",
        country: "France",
        notes: "French-speaking client, requires invoices in French.",
        createdAt: "2025-03-10",
        totalBilled: 9200,
        projectIds: ["p2"],
    },
    {
        id: "c3",
        name: "Marcus Weber",
        company: "HealthApp GmbH",
        email: "m.weber@healthapp.de",
        timezone: "Europe/Berlin",
        country: "Germany",
        notes: "Very technical. Loves clean code and documentation.",
        createdAt: "2025-06-01",
        totalBilled: 14500,
        projectIds: ["p3"],
    },
];

// ─── Mock Projects ────────────────────────────────────────────────────────────
export const mockProjects: Project[] = [
    {
        id: "p1",
        name: "TechStart Landing Page + CMS",
        description: "Full marketing site with headless CMS and contact form integration.",
        clientId: "c1",
        clientName: "TechStart Tunis",
        status: "delivered",
        startDate: "2025-01-20",
        dueDate: "2025-02-28",
        deliveredDate: "2025-02-25",
        contractValue: 4800,
        paymentType: "fixed",
        advancePaid: 2400,
        remainingBalance: 0,
        paymentStatus: "paid",
        currency: "USD",
        stack: ["Next.js", "Sanity", "Tailwind CSS", "Vercel"],
        tags: ["landing-page", "cms", "marketing"],
        createdAt: "2025-01-15",
        updatedAt: "2025-03-01",
        caseStudyId: "cs1",
    },
    {
        id: "p2",
        name: "EcomParis Store Rebuild",
        description: "Full e-commerce rebuild from WooCommerce to Next.js + Stripe.",
        clientId: "c2",
        clientName: "EcomParis",
        status: "review",
        startDate: "2025-03-15",
        dueDate: "2026-04-30",
        contractValue: 9200,
        paymentType: "fixed",
        advancePaid: 4600,
        remainingBalance: 4600,
        paymentStatus: "partial",
        currency: "USD",
        stack: ["Next.js", "Stripe", "Prisma", "PostgreSQL", "Vercel"],
        tags: ["ecommerce", "stripe", "rebuild"],
        createdAt: "2025-03-10",
        updatedAt: "2026-03-01",
    },
    {
        id: "p3",
        name: "HealthApp Patient Dashboard",
        description: "HIPAA-compliant patient-facing dashboard with appointment booking.",
        clientId: "c3",
        clientName: "HealthApp GmbH",
        status: "active",
        startDate: "2026-01-10",
        dueDate: "2026-05-30",
        contractValue: 14500,
        paymentType: "fixed",
        advancePaid: 7250,
        remainingBalance: 7250,
        paymentStatus: "partial",
        currency: "USD",
        stack: ["React", "Node.js", "PostgreSQL", "Supabase", "Tailwind CSS"],
        tags: ["health", "dashboard", "saas"],
        createdAt: "2026-01-05",
        updatedAt: "2026-03-08",
    },
];

// ─── Mock Leads ───────────────────────────────────────────────────────────────
export const mockLeads: Lead[] = [
    {
        id: "l1",
        companyName: "RetailPro Morocco",
        contactName: "Karim Mansouri",
        contactEmail: "k.mansouri@retailpro.ma",
        stage: "proposal",
        estimatedValue: 6500,
        currency: "USD",
        source: "LinkedIn",
        nextActionDate: "2026-03-12",
        lastContactDate: "2026-03-05",
        notes: "Interested in a full POS + inventory management web app.",
        tags: ["pos", "saas", "retail"],
        createdAt: "2026-02-28",
        updatedAt: "2026-03-05",
    },
    {
        id: "l2",
        companyName: "LegalDoc AI",
        contactName: "Leila Trabelsi",
        contactEmail: "leila@legaldoc.ai",
        contactLinkedIn: "linkedin.com/in/leilatrabelsi",
        stage: "discovery",
        estimatedValue: 22000,
        currency: "USD",
        source: "Referral",
        nextActionDate: "2026-03-15",
        lastContactDate: "2026-03-07",
        notes: "Building an AI-powered document automation SaaS. Very promising lead.",
        tags: ["ai", "saas", "legal"],
        createdAt: "2026-03-06",
        updatedAt: "2026-03-07",
    },
    {
        id: "l3",
        companyName: "FitLife Gyms",
        contactName: "Mohamed Chaari",
        contactEmail: "m.chaari@fitlife.tn",
        stage: "negotiation",
        estimatedValue: 8000,
        currency: "USD",
        source: "Website",
        nextActionDate: "2026-03-10",
        lastContactDate: "2026-03-06",
        notes: "Member management + class booking app. Final proposal sent, waiting on budget approval.",
        tags: ["fitness", "mobile", "booking"],
        createdAt: "2026-02-20",
        updatedAt: "2026-03-06",
    },
    {
        id: "l4",
        companyName: "CloudPrint SaaS",
        contactName: "Emma Laurent",
        stage: "discovery",
        estimatedValue: 12000,
        currency: "USD",
        source: "Cold-outreach",
        lastContactDate: "2026-03-01",
        notes: "Print-on-demand SaaS for SMBs. Early stage.",
        tags: ["saas", "b2b"],
        createdAt: "2026-03-01",
        updatedAt: "2026-03-01",
    },
];

// ─── Mock Finance Records ─────────────────────────────────────────────────────
export const mockFinances: FinanceRecord[] = [
    {
        id: "f1",
        projectId: "p1",
        projectName: "TechStart Landing Page + CMS",
        clientName: "TechStart Tunis",
        type: "income",
        description: "Advance payment (50%)",
        amount: 2400,
        currency: "USD",
        date: "2025-01-20",
        paymentStatus: "paid",
    },
    {
        id: "f2",
        projectId: "p1",
        projectName: "TechStart Landing Page + CMS",
        clientName: "TechStart Tunis",
        type: "income",
        description: "Final payment (50%)",
        amount: 2400,
        currency: "USD",
        date: "2025-02-27",
        paymentStatus: "paid",
    },
    {
        id: "f3",
        projectId: "p2",
        projectName: "EcomParis Store Rebuild",
        clientName: "EcomParis",
        type: "income",
        description: "Advance payment (50%)",
        amount: 4600,
        currency: "USD",
        date: "2025-03-15",
        paymentStatus: "paid",
    },
    {
        id: "f4",
        projectId: "p2",
        projectName: "EcomParis Store Rebuild",
        clientName: "EcomParis",
        type: "income",
        description: "Final payment (50%) — due on delivery",
        amount: 4600,
        currency: "USD",
        date: "2026-04-30",
        paymentStatus: "pending",
    },
    {
        id: "f5",
        projectId: "p3",
        projectName: "HealthApp Patient Dashboard",
        clientName: "HealthApp GmbH",
        type: "income",
        description: "Advance payment (50%)",
        amount: 7250,
        currency: "USD",
        date: "2026-01-10",
        paymentStatus: "paid",
    },
    {
        id: "f6",
        projectId: "p3",
        projectName: "HealthApp Patient Dashboard",
        clientName: "HealthApp GmbH",
        type: "income",
        description: "Final payment (50%) — due on delivery",
        amount: 7250,
        currency: "USD",
        date: "2026-05-30",
        paymentStatus: "pending",
    },
];

// ─── Mock Case Studies ────────────────────────────────────────────────────────
export const mockCaseStudies: CaseStudy[] = [
    {
        id: "cs1",
        slug: "techstart-landing-page",
        title: "TechStart Tunis — Marketing Site That Converts",
        subtitle: "Built a lightning-fast marketing site with a no-code CMS for a Tunis-based startup.",
        client: "TechStart Tunis",
        category: "web-app",
        stack: ["Next.js", "Sanity", "Tailwind CSS", "Vercel"],
        coverImage: "/case-studies/techstart-cover.webp",
        images: [],
        problem: "TechStart had a static HTML site with no way to update content without a developer. They were losing leads due to slow load times and no clear CTAs.",
        solution: "We rebuilt the site in Next.js with a Sanity headless CMS, allowing non-technical staff to update content instantly. We optimized for Core Web Vitals and SEO.",
        outcome: "The new site achieved a 94 Lighthouse score, and leads increased by 140% in the first quarter after launch.",
        metrics: [
            { label: "Lighthouse Score", value: "94/100" },
            { label: "Lead increase", value: "+140%" },
            { label: "Time to launch", value: "5 weeks" },
            { label: "Contract value", value: "$4,800" },
        ],
        projectId: "p1",
        featured: true,
        publishedAt: "2025-03-01",
    },
    {
        id: "cs2",
        slug: "healthapp-patient-dashboard",
        title: "HealthApp GmbH — Patient Dashboard",
        subtitle: "A full-featured patient portal with appointment booking and secure health records.",
        client: "HealthApp GmbH",
        category: "saas",
        stack: ["React", "Node.js", "PostgreSQL", "Supabase"],
        coverImage: "/case-studies/healthapp-cover.webp",
        images: [],
        problem: "HealthApp's patients had no way to manage appointments or view their health history online — everything was done by phone.",
        solution: "Built a secure, HIPAA-aligned patient dashboard with appointment scheduling, health record access, and real-time notifications.",
        outcome: "Reduced phone appointment bookings by 68% in 3 months, saving the clinic 20+ staff hours per week.",
        metrics: [
            { label: "Phone bookings reduced", value: "-68%" },
            { label: "Staff hours saved/week", value: "20+" },
            { label: "Active users at launch", value: "350+" },
            { label: "Contract value", value: "$14,500" },
        ],
        projectId: "p3",
        featured: true,
        publishedAt: "2026-03-08",
    },
];

// ─── Dashboard KPIs ───────────────────────────────────────────────────────────
export const mockKPIs: DashboardKPIs = {
    monthlyRevenue: 7250,
    revenueChange: 28,
    activeProjects: 2,
    openLeads: 4,
    overdueInvoices: 0,
    totalOutstanding: 11850,
};

// ─── Monthly revenue chart data ───────────────────────────────────────────────
export const monthlyRevenue = [
    { month: "Apr", revenue: 0 },
    { month: "May", revenue: 0 },
    { month: "Jun", revenue: 0 },
    { month: "Jul", revenue: 0 },
    { month: "Aug", revenue: 0 },
    { month: "Sep", revenue: 0 },
    { month: "Oct", revenue: 0 },
    { month: "Nov", revenue: 0 },
    { month: "Dec", revenue: 0 },
    { month: "Jan", revenue: 4800 },
    { month: "Feb", revenue: 4600 },
    { month: "Mar", revenue: 7250 },
];
